### ISSUE TITLE
Fails to retrieve User ID

### ISSUE THREAD

**Issue by adam-CG** [umich-brcf-bioinf/Connor#7]
When running Connor in a Docker container Connor dies trying to set the User ID for logging purposes:
```
An unexpected error occurred
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/connor/connor.py", line 159, in main
    log = utils.Logger(args)
  File "/opt/conda/lib/python3.6/site-packages/connor/utils.py", line 86, in __init__
    user = getpass.getuser()
  File "/opt/conda/lib/python3.6/getpass.py", line 169, in getuser
    return pwd.getpwuid(os.getuid())[0]
KeyError: 'getpwuid(): uid not found: *myuserid*'
```

**Comment by cgates** [comment]
Thanks for pointing this out. We will fix this asap.

**Comment by cgates** [comment]
Hi adam-CG,
Version 0.6.1 (released tonight) should avoid this problem. Let us know if otherwise.
Thanks again for the feedback.
Best,
cg
